from __future__ import annotations

# 0-based indices (matching your TS config)

INSTRUCTIONS_SHEET_NAME = "Instructions"
INSTRUCTIONS_DATE_A1 = "A1"

DB_SHEET_NAME = "Database (read only)"
TRASH_SHEET_NAME = "Trash"
ADD_SHEET_NAME = "Add"

NEW_ID_SHEET_NAME = "New IDs"
NEW_ID_LAST_ID_A1 = "A1"

# ADD sheet columns (0-based)
ADD_READY_TO_COMMIT = 0
ADD_MUSEUM_NAME = 1
ADD_ALTERNATIVE_NAME = 2
ADD_WIKIDATA_ID = 3
ADD_ADDRESS_1 = 4
ADD_ADDRESS_2 = 5
ADD_ADDRESS_3 = 6
ADD_VILLAGE_TOWN_CITY = 7
ADD_POSTCODE = 8
ADD_ACCREDITATION = 9
ADD_ACCREDITATION_NUMBER = 10
ADD_ACCREDITATION_CHANGE_DATE = 11
ADD_GOVERNANCE = 12
ADD_GOVERNANCE_SOURCE = 13
ADD_PREVIOUS_GOVERNANCE = 14
ADD_PREVIOUS_GOVERNANCE_START = 15
ADD_PREVIOUS_GOVERNANCE_END = 16
ADD_SIZE = 17
ADD_SIZE_SOURCE = 18
ADD_SUBJECT = 19
ADD_YEAR_OPENED = 20
ADD_YEAR_OPENED_SOURCE = 21
ADD_YEAR_CLOSED = 22
ADD_YEAR_CLOSED_SOURCE = 23
ADD_PRIMARY_PROVENANCE_OF_DATA = 24
ADD_NOTES = 25

ADD_LAST_COL_INDEX = 25  # inclusive

# DB sheet columns (0-based)
DB_ID = 0
DB_MUSEUM_NAME = 1
DB_ALTERNATIVE_NAME = 2
DB_WIKIDATA_ID = 3
DB_ADDRESS_1 = 4
DB_ADDRESS_2 = 5
DB_ADDRESS_3 = 6
DB_VILLAGE_TOWN_CITY = 7
DB_POSTCODE = 8
DB_ACCREDITATION = 9
DB_ACCREDITATION_NUMBER = 10
DB_ACCREDITATION_CHANGE_DATE = 11
DB_GOVERNANCE_BROAD = 12
DB_GOVERNANCE = 13
DB_GOVERNANCE_SOURCE = 14
DB_PREVIOUS_GOVERNANCE = 15
DB_PREVIOUS_GOVERNANCE_START = 16
DB_PREVIOUS_GOVERNANCE_END = 17
DB_SIZE = 18
DB_SIZE_SOURCE = 19
DB_SUBJECT_BROAD = 20
DB_SUBJECT = 21
DB_YEAR_OPENED_1 = 22
DB_YEAR_OPENED_2 = 23
DB_YEAR_OPENED_SOURCE = 24
DB_YEAR_CLOSED_1 = 25
DB_YEAR_CLOSED_2 = 26
DB_YEAR_CLOSED_SOURCE = 27
DB_PRIMARY_PROVENANCE_OF_DATA = 28
DB_NOTES = 29

DB_TOTAL_COLS = 30
