---
title: "Taxonomies"
output: html_notebook
---

```{r}
library(janitor)
library(ggplot2)
library(igraph)
library(ggraph)
library(tidyverse)
library(readr)

taxonomy_theme <- theme(
  panel.background = element_rect(fill="white"),
  plot.margin = unit(c(1, 1, 1, 1), "cm"),
  plot.title = element_text(size="18"),
  legend.position = "right",
  legend.title = element_text(size="12"),
  legend.text = element_text(size="8"),
  legend.background = element_rect(fill="white"),
  legend.key = element_rect(fill="white")
)

output_width <- 175
output_height <- 270
output_units <- "mm"
```

## helper functions
```{r}
add_dummies <- function(table) {
  table <- table |> mutate(is_dummy=FALSE)
  counter <- 1
  types_with_sub_types <- table |>
    filter(!is.na(sub_type_of)) |>
    select(type_name=sub_type_of) |>
    distinct()
  for (i in 1:nrow(types_with_sub_types)) {
    new_row_1 <- data.frame(
      type_name = as.character(counter),
      sub_type_of = types_with_sub_types$type_name[i],
      is_core_category = FALSE,
      is_dummy = TRUE
    )
    new_row_2 <- data.frame(
      type_name = paste("z", as.character(counter)),
      sub_type_of = types_with_sub_types$type_name[i],
      is_core_category = FALSE,
      is_dummy = TRUE
    )
    counter <- counter + 1
    table <- table |>
      rbind(new_row_1) |>
      rbind(new_row_2)
  }
  table
}

get_taxonomy_layout <- function(types, root_name) {
  core_types <- types |>
    filter(is_core_category) |>
    select(type_name)
  dummy_types <- types |>
    filter(is_dummy) |>
    select(type_name)
  edges <- types |>
    arrange(sub_type_of, type_name) |>
    filter(!is.na(sub_type_of), sub_type_of != "") |>
    select(
      from=sub_type_of,
      to=type_name
    ) |>
    mutate(is_to_dummy = to %in% dummy_types$type_name)
  print(edges)
  graph <- graph_from_data_frame(edges, directed=TRUE)
  print(graph |> igraph::edge_attr_names())
  V(graph)$distance_to_root <- distances(graph, v=V(graph), to=which(V(graph)$name == root_name))
  max_distance <- max(V(graph)$distance_to_root)
  layout <- create_layout(graph, layout="dendrogram", circular=FALSE) |>
    left_join(types |> select(name=type_name, is_core_category), by="name")
  layout$y <- layout$distance_to_root - max_distance
  layout$is_core_category <- layout$name %in% core_types$type_name
  layout$is_dummy <- layout$name %in% dummy_types$type_name
  layout
}

get_taxonomy <- function(layout) {
  ggraph(layout) + 
    geom_edge_diagonal(
      aes(colour = ifelse(is_to_dummy, "dummy", "normal")),
      show.legend=FALSE
    ) +
    geom_node_point(
      data=layout |> filter(!is_dummy),
      aes(colour=is_core_category),
      shape=21,
      size=2,
      stroke=1,
      fill="white"
    ) +
    geom_node_text(
      data=layout |> filter(!is_dummy),
      aes(label=name),
      size=2,
      angle=0,
      vjust="center",
      hjust="left",
      nudge_y=0.05
    ) +
    coord_flip() +
    scale_y_continuous(limits=c(-max_distance, 1)) +
    scale_colour_manual(
      values=c("TRUE"="black", "FALSE"="lightgrey"),
      labels=c("TRUE"="core categories", "FALSE"="sub-categories"),
      name=""
    ) +
    scale_edge_colour_manual(
      values=c("dummy"="white", "normal"="lightgrey")
    ) +
    guides(
      colour=guide_legend(order=2, override.aes=list(fill=NA))
    ) +
    taxonomy_theme
}
```

```{r}
actor_types_csv <- "../data-model/actor_types.csv"
actor_types <- read_csv(actor_types_csv) |>
  select(type_name, sub_type_of, is_core_category) |>
  add_dummies()
actors_layout <- get_taxonomy_layout(actor_types, "actor")
actors_taxonomy <- get_taxonomy(actors_layout)
ggsave("figures/taxonomy-actors.svg", actors_taxonomy, width=output_width, height=output_height, units=output_units, bg="white")
actors_taxonomy
```

### Events Taxonomy
```{r}
event_types_csv <- "../data-model/event_types.csv"
event_types <- read_csv(event_types_csv) |>
  select(type_name, sub_type_of, is_core_category) |>
  add_dummies()
events_layout <- get_taxonomy_layout(event_types, "event")
events_taxonomy <- get_taxonomy(events_layout)
ggsave("figures/taxonomy-events.svg", events_taxonomy, width=output_width, height=output_height, units=output_units, bg="white")
events_taxonomy
```

### reasons taxonomy
```{r}
closure_reasons_raw <- read_csv("../data/closure_data/super_events.csv") |>
  separate_rows(reason, sep = "; ") |>
  separate_wider_delim(
    reason,
    " - ",
    names=c("core_reason", "sub_core_reason", "specific_reason"),
    too_few="align_start"
  ) |>
  select(specific_reason, sub_core_reason, core_reason) |>
  distinct()

core_reasons <- closure_reasons_raw |>
  select(type_name=core_reason) |>
  distinct() |>
  mutate(sub_type_of="reason", is_core_category=TRUE) |>
  select(type_name, sub_type_of, is_core_category)
sub_core_reasons <- closure_reasons_raw |>
  select(type_name=sub_core_reason, sub_type_of=core_reason) |>
  distinct() |>
  mutate(is_core_category=FALSE) |>
  select(type_name, sub_type_of, is_core_category)
specific_reasons <- closure_reasons_raw |>
  select(type_name=specific_reason, sub_type_of=sub_core_reason) |>
  distinct() |>
  mutate(is_core_category=FALSE) |>
  select(type_name, sub_type_of, is_core_category)

closure_reasons <- data.frame(type_name=c("reason"), sub_type_of=c(NA), is_core_category=c(FALSE)) |>
  rbind(core_reasons) |>
  rbind(sub_core_reasons) |>
  rbind(specific_reasons) |>
  filter(!is.na(type_name)) |>
  filter(!type_name %in% c("disagreement", "theft")) |>
  add_dummies()

reasons_layout <- get_taxonomy_layout(closure_reasons, "reason")
print(reasons_layout)
reasons_taxonomy <- get_taxonomy(reasons_layout)
ggsave("figures/taxonomy-reasons.svg", reasons_taxonomy, width=output_width, height=output_height, units=output_units, bg="white")
reasons_taxonomy
```